export const AUTH_CHECK = "AUTH_CHECK";
export const AUTH_CHECK_SUCCESS = "AUTH_CHECK_SUCCESS";
export const AUTH_CHECK_ERROR = "AUTH_CHECK_ERROR";

export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";

export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export const LOG_OUT_USER = "LOG_OUT_USER";
export const LOG_OUT_USER_SUCCESS = "LOG_OUT_USER_SUCCESS";
export const LOG_OUT_USER_ERROR = "LOG_OUT_USER_ERROR";
